/-
  Continuum.Enumeration
  Injective constructors used to count fixed-length palindromes.
-/

import Continuum.Common

namespace Continuum

/-- Repeating a digit in the two base-b positions never identifies two distinct digits. -/
theorem two_digit_palindrome_constructor_injective (base : Nat) (hbase : base >= 2) :
    Function.Injective (fun digit : Nat => base * digit + digit) := by
  intro a b h
  have hfactor : (base + 1) * a = (base + 1) * b := by
    simpa [Nat.add_mul] using h
  have hpositive : 0 < base + 1 := by omega
  exact Nat.mul_left_cancel hpositive hfactor

/-- The canonical two-digit palindrome values generated by digits `1, ..., base - 1`. -/
def twoDigitPalindromeValues (base : Nat) : List Nat :=
  (List.range (base - 1)).map (fun offset =>
    base * (offset + 1) + (offset + 1))

/-- In every valid base, the canonical enumeration has `base - 1` distinct values. -/
theorem two_digit_palindrome_count (base : Nat) (hbase : base >= 2) :
    (twoDigitPalindromeValues base).length = base - 1 ∧
      (twoDigitPalindromeValues base).Nodup := by
  constructor
  · simp [twoDigitPalindromeValues]
  · unfold twoDigitPalindromeValues
    change List.Pairwise (fun a b => a ≠ b)
      ((List.range (base - 1)).map
        (fun offset => base * (offset + 1) + (offset + 1)))
    rw [List.pairwise_map]
    exact (List.nodup_range).imp (by
      intro a b hab
      intro heq
      have hsucc : a + 1 = b + 1 :=
        two_digit_palindrome_constructor_injective base hbase heq
      exact hab (by omega))

end Continuum
